export const SET_FIXED_COST = "SET_FIXED_COST";
export const SET_VARIABLE_COSTS = "SET_VARIABLE_COSTS";
export const INSERT_VARIABLE_COST = "INSERT_VARIABLE_COST"
export const SET_RECIPES = "SET_RECIPES"
export const INSERT_RECIPE = "INSERT_RECIPE"
export const SET_ORDERS = "SET_ORDERS"